gaofeisys/urls.py
from django.contrib import admin
from django.urls import path,include

import  sellSys.views as sv
import  purchaseSys.views as pv
import readJineng.views as rv1

#题库
import  readxls.views as rv

import lilun.views as lv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userinfo/', include('userInfo.urls')),
    path('purSysIndex/', include('purchaseSys.urls')),

    path('sellSysIndex/',include('sellSys.urls')),

    # path('',sv.sellIndex),
    # path('',pv.cangkuquery)

    path('xlsshow/',rv.show),
    path('', rv1.showjineng),
    path('showjineng1/',rv1.showjineng1),
    path('showlilun/',lv.showLilun),




]

sellSys/urls.py
from django.contrib import admin
from django.urls import path,include

import  sellSys.views as sv

urlpatterns = [
    path('sellIndex/',sv.sellIndex),
    path('sellorder/',sv.sellorder ),

]

userInfo/urls.py
from django.contrib import admin
from django.urls import path

import userInfo.views as uv

#userInfo
urlpatterns = [
    path('login/', uv.login),
    path('register/', uv.register),
    path('register/ajax1_getImgUrl/', uv.ajax1_getImgUrl),
]

userInfo/models.py
from django.db import models

# Create your models here.
class User( models.Model):
    uname = models.CharField(max_length=20,unique=True)
    upwd = models.CharField(max_length=20)
    ulev = models.IntegerField(default=2)   #默认待审核
    utel = models.CharField(max_length=11)
    uaddr = models.CharField(max_length=32)
    uimg = models.CharField(max_length=100)

userInfo/forms.py
from django import forms
from django.forms import fields
from django.forms import widgets

from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from userInfo.models import User

#登录组件
class UserForm(forms.Form):
    uname = fields.CharField(max_length=20,min_length=1,label='用户名',required=True)
    upwd = fields.CharField(max_length=20,min_length=1,label='密码',required=True,widget=widgets.PasswordInput)

#注册组件
class RegisterForm(forms.Form):
    uname = fields.CharField(max_length=20, min_length=1, label='用户名', required=True,widget=widgets.TextInput(attrs={'class':'form-control'}))
    upwd = fields.CharField(max_length=20, min_length=1, label='密码', required=True,widget=widgets.PasswordInput(attrs={'class':'form-control','id':'exampleInputPassword1'}))
    ulev = fields.ChoiceField(
        choices=((0,'超级用户'),(1,'普通用户'),(2,'待审核用户')),
        initial=2,
        # widget=widgets.RadioSelect,
        label='类别',
        widget = widgets.Select(attrs={'readonly':True,'class':'form-control'}),

    )
    utel = fields.CharField(max_length=11,min_length=11,label='电话',widget=widgets.NumberInput(attrs={'class':'form-control'}))
    uaddr = fields.CharField(max_length=32,label='地址',widget=widgets.TextInput(attrs={'class':'form-control'}))
    uimg = fields.ImageField(label='图片',widget=widgets.FileInput(attrs={'id':'exampleInputFile'}))

    #图片验证
    def clean_uimg(self):
        value = self.cleaned_data['uimg']
        if value.name.split('.')[-1] not in ['jpg','png']:
            raise ValidationError('只能录入jpg,png格式的图片')
        else:
            return value

    #用户验证
    def clean_uname(self):
        value = self.cleaned_data['uname']
        print('---',value)
        if User.objects.filter(uname=value):
            raise  ValidationError('该用户已经存在')
        else:
            return value

userInfo/views.py
from django.shortcuts import render,HttpResponse,redirect

from userInfo.models import User
from userInfo.forms import UserForm,RegisterForm
import random,string,os
from django.conf import settings
import json

# Create your views here.
#登录处理
def login(request):
    if request.method == 'GET':
        userform = UserForm()
        return render(request,'userInfo/login.html',locals())
    else:
        userform = UserForm(request.POST)
        if userform.is_valid():
            loginData = userform.cleaned_data
            if User.objects.filter(uname=loginData.get('uname'),upwd=loginData.get('upwd')):
                return HttpResponse('登录成功')
            else:
                return HttpResponse('登录失败')
        else:
            return render(request,'userInfo/login.html',locals())

#注册处理
def register(request):
    if request.method == 'GET':
        regform = RegisterForm()
        return render(request,'userInfo/register.html',locals())
    else:
        regform = RegisterForm(request.POST,request.FILES)  #生成组件验证对象
        print(request.POST)      #110
        print(request.FILES)      #110
        if regform.is_valid():
            regdata = regform.cleaned_data  #验证后的所有数据
            print(regdata)

            # 处理保存图片
            uimg = regdata.get('uimg')
            uimg_name_url = request.session.get('uimg','')
            if not uimg_name_url:
                random_name =  ''.join(random.choices(string.ascii_letters + string.digits,k=10)) + '_'+ uimg.name  #随机名称
                uimg_name_url = os.path.join(settings.STATICFILES_DIRS[1],random_name)
                print(uimg_name_url)    #110
                write_to_file(uimg_name_url, uimg)
                request.session['uimg'] = uimg_name_url = '/static/'+random_name

            #保存注册记录
            print(regdata)  # 110
            datadict = {
                'uname': regdata.get('uname'),
                'upwd' :regdata.get('upwd'),
                'ulev' :int(regdata.get('ulev').strip()),
                'utel' :regdata.get('utel'),
                'uaddr': regdata.get('uaddr'),
                'uimg' :uimg_name_url,
            }
            User.objects.create(**datadict)
            print(datadict)     #110保存的数据字典
            return redirect('/userinfo/login/')
        else:
            return render(request,'userInfo/register.html',locals())

def write_to_file(uimg_name_url,uimg):#保存路径,文件对象
    print(uimg_name_url)  # 110
    with open(uimg_name_url, 'wb') as fw:
        for line in uimg.chunks():
            fw.write(line)

#异步 上传图片返回图片路径
def ajax1_getImgUrl(request):
    uimg = request.FILES.get('file')
    # print(dir(file))

    random_name = ''.join(random.choices(string.ascii_letters + string.digits, k=10)) + '_' + uimg.name     #随机名字
    uimg_name_url = os.path.join(settings.STATICFILES_DIRS[1],random_name)

    print(uimg_name_url)  # 110
    write_to_file(uimg_name_url, uimg)     #保存文件
    server_request_url = '/static/'+random_name

    request.session['uimg'] = server_request_url        #将图片保存到session中

    return HttpResponse(json.dumps(server_request_url))




    # return render(request,'userInfo/register.html',locals())

userInfo/templates/userInfo/base1.html
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
<script src="/static/bootstrap/js/jquery-2.1.4.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.js"></script>

userInfo/templates/userInfo/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'userInfo/base1.html' %}
    <title>登录</title>
</head>
<body>
    <form action="" method="post" >
        {% csrf_token %}
        <table align="center">
            <tr>
                <td>{{ userform.uname.label }}</td>
                <td>{{ userform.uname }}{{ userform.errors.uname.0 }}</td>
            </tr>
            <tr>
                <td>{{ userform.upwd.label }}</td>
                <td>{{ userform.upwd }}</td>
            </tr>
            <tr align="center">
                <td colspan="2">
                    <input type="submit" value="登录">
                    <button onclick="goRegister();return false;">注册</button>
                </td>
            </tr>
        </table>
    </form>

    <script>
        function goRegister() {
            window.location.href = '/userinfo/register/'
        }
        
    </script>
</body>
</html>

userInfo/templates/userInfo/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'userInfo/base1.html' %}
    <title>注册</title>
</head>
<body>
        <div id="outer">
        <form action=""  method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="form-group col-xs-10">
                    <label for="exampleInputEmail1">{{ regform.uname.label }}</label>
                    {{ regform.uname }}{% if regform.errors.uname.0 != None %}<span class="glyphicon glyphicon-remove-circle bg-danger" style="color:red;">{{ regform.errors.uname.0 }}</span>{% endif %}
                </div>
                <div class="form-group col-xs-10">
                    <label for="exampleInputEmail1">{{ regform.upwd.label }}</label>
                    {{ regform.upwd }}{% if regform.errors.upwd.0 != None %}<span class="glyphicon glyphicon-remove-circle text-danger" style="color:red;">{{ regform.errors.upwd.0 }}</span>{% endif %}
                </div>
                <div class="form-group col-xs-10">
                    <label for="exampleInputEmail1">{{ regform.ulev.label }}</label>
                    {{ regform.ulev }}{% if regform.errors.ulev.0 != None %}<span class="glyphicon glyphicon-remove-circle text-danger" style="color:red;">{{ regform.errors.ulev.0 }}</span>{% endif %}
                </div>
                <div class="form-group col-xs-10">
                    <label for="exampleInputEmail1">{{ regform.utel.label }}</label>
                    {{ regform.utel }}{% if regform.errors.utel.0 != None %}<span class="glyphicon glyphicon-remove-circle text-danger" style="color:red;">{{ regform.errors.utel.0 }}</span>{% endif %}
                </div>
                <div class="form-group col-xs-10">
                    <label for="exampleInputEmail1">{{ regform.uaddr.label }}</label>
                    {{ regform.uaddr }}{% if regform.errors.uaddr.0 != None %}<span class="glyphicon glyphicon-remove-circle text-danger" style="color:red;">{{ regform.errors.uaddr.0 }}</span>{% endif %}
                </div>
                <div class="form-group col-xs-10">
                    <label for="exampleInputEmail1">{{ regform.uimg.label }}</label>
                    <input type="file" name="uimg" required="" id="id_uimg" onchange="uploadFile();">{% if regform.errors.uimg.0 != None %}<span class="glyphicon glyphicon-remove-circle text-danger" style="color:red;">{{ regform.errors.uimg.0 }}</span>{% endif %}
                    <p class="help-block">Example block-level help text here.</p>
                    <p><img src="" style="display:none;border: 1px solid black;" alt="上传图片" id="uploadimg" class="img-thumbnail" width="80" height="80"></p>
                </div>
                <td colspan="2" align="center"><input type="submit" value=" 注册 " class="btn btn-success"><button class="btn btn-info" onclick="goLogin();return false;"> 返回 </button>
        </form>

        </div>
    </table>
        <style>
            .col-xs-10{
                float: none;
            }
            #outer{
                margin: 0 auto;
                width: 35%;

            }
            .btn{
                width: 60px;
                height: 35px;
                margin-left: 16%;
            }
            .glyphicon {
                position: relative;
                top: 2px;
                display: inline-block;
                font-style: italic;
                font-weight: normal;
                line-height: 1;
                -webkit-font-smoothing: antialiased;
            }
        </style>
    <script>
        function uploadFile() {
            var data = new FormData()
            var file = document.getElementById('id_uimg').files[0]
            console.log(file)

            data.append('file',file)
            $.ajax({
                url: '/userinfo/register/ajax1_getImgUrl/',
                type: 'post',
                data: data,
                dataType: 'json',
                success: function (arg) {
                    console.log(arg)
                    $('#uploadimg').prop('src',arg)
                    $('#uploadimg').css('display','inline-block')

                },
                processData:false,      //组织jquery过多的处理FormData数据
                contentType:false
            })
        }
        
        function goLogin() {
            window.location.href = '/userinfo/login/'
        }
    </script>
</body>
</html>