gaofeisys/urls.py
from django.contrib import admin
from django.urls import path,include

import  sellSys.views as sv
import  purchaseSys.views as pv
import readJineng.views as rv1

#题库
import  readxls.views as rv

import lilun.views as lv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userinfo/', include('userInfo.urls')),
    path('purSysIndex/', include('purchaseSys.urls')),

    path('sellSysIndex/',include('sellSys.urls')),

    # path('',sv.sellIndex),
    # path('',pv.cangkuquery)

    path('xlsshow/',rv.show),
    path('', rv1.showjineng),
    path('showjineng1/',rv1.showjineng1),
    path('showlilun/',lv.showLilun),




]

sellSys/urls.py
from django.contrib import admin
from django.urls import path,include

import  sellSys.views as sv

urlpatterns = [
    path('sellIndex/',sv.sellIndex),
    path('sellorder/',sv.sellorder ),

]

lilun/models.py
from django.db import models
from django.forms import fields
from django.forms import  widgets
from django import forms

# Create your models here
class Lilun(models.Model):
    name = models.CharField(max_length=100)
    content = models.CharField(max_length=100)

class LilunForm(forms.Form):
    name = fields.ChoiceField(
        choices=Lilun.objects.values_list('id','name'),
        widget=widgets.Select(attrs={'class': 'form-control','style':'width:30%;display:inline-block;'}),
    )

readJineng/models.py
from django.db import models
from django.forms import fields
from django.forms import  widgets
from django import forms
import re

# Create your models here.
# 技能
class Exam_jineng(models.Model):
    title = models.CharField(max_length=200)    #技能主題
    title_content = models.TextField()  #技能內容
    daima = models.TextField()  #技能代码

class Exam_jinengForm(forms.Form):
    exam_titles = Exam_jineng.objects.values_list('id', 'title')
    exam_titles1 = [i for i in exam_titles if not re.search(r'月考|周考',i[1])]
    exam_titles2 = [i for i in exam_titles if re.search(r'月考|周考',i[1])]
    # exam_titles1 = sorted(exam_titles1,key=lambda x:int(re.search(r'[-_]\w*(\d*)\w*[.|_]*',x[1]).group(1)),reverse=False)
    exam_titles1 = sorted(exam_titles1,key=lambda x:int(re.search(r'[-_][\u4e00-\u9fa5]*(\d+)\w+',x[1]).group(1)),reverse=False)
    exam_titles = exam_titles1 + exam_titles2

    print(Exam_jineng.objects.values('id','title'))
    title = fields.ChoiceField(
        choices=exam_titles,
        widget=widgets.Select(attrs={'class': 'form-control', 'style': 'width:60%;display:inline-block;','id':'id_jineng'}),
    )

readxls/models.py
from django.db import models
from django.forms import fields
from django.forms import  widgets
from django import forms

# Create your models here.
#试卷
class Exam(models.Model):
    kaoti = models.ForeignKey('Kaoti',on_delete=models.CASCADE)

    bianhao = models.IntegerField()
    zhishidian = models.CharField(max_length=20)  #知识点
    leixing =   models.CharField(max_length=20)  #类型
    tigan =     models.CharField(max_length=200)  #题干
    xxa =       models.TextField()  #选项A
    xxb =       models.TextField()  #选项B
    xxc =       models.TextField()  #选项C
    xxd =       models.TextField()  #选项D
    xxe =       models.TextField()  #选项E
    xxf =       models.TextField()  #选项F
    daan =      models.CharField(max_length=100) #答案
    jiexi =     models.CharField(max_length=100)   #解析
    chutiren =  models.CharField(max_length=100) #出题人

#试卷名称
class Kaoti(models.Model):
    name = models.CharField(max_length=100)


import re
class KaotiForm(forms.Form):
    kaoti_titiles = tuple(Kaoti.objects.values_list('id', 'name'))
    kaoti_titiles1 = [i  for i in kaoti_titiles if not re.search(r'(月考|周考)',i[1])]
    kaoti_titiles2 = [i  for i in kaoti_titiles if re.search(r'(月考|周考)',i[1])]
    kaoti_titiles1 = sorted(kaoti_titiles1,key=lambda x:int(re.search(r'[-_](\d*)[.|_]*',x[1]).group(1)),reverse=False)
    kaoti_titiles1 += kaoti_titiles2

    kaoti_titiles3 = []
    for i in range(len(kaoti_titiles1)):
        kaoti_titiles3.append((kaoti_titiles1[i][0],str(i+1).rjust(2,'0')+'-' + kaoti_titiles1[i][1]))
    print(kaoti_titiles3)

    kaoti = fields.ChoiceField(
        choices=kaoti_titiles3,
        widget=widgets.Select(attrs={'class': 'form-control','style':'width:60%;display:inline-block;'}),
    )
# class KaotiForm(forms.Form):
#     name = fields.

readJineng/views.py
from django.shortcuts import render,HttpResponse
from readJineng.models import Exam_jineng,Exam_jinengForm
import os,xlrd
import docx
import json
from readxls.models import Exam,Kaoti,KaotiForm
from lilun.models import Lilun,LilunForm

def writeToDB(docxpath):
    basename = os.path.basename(docxpath)  # 获取文件名
    title =  basename
    content = ''
    document = docx.Document(docxpath)
    # print('=========',path)

    for para in document.paragraphs:
        content += '\n' + para.text
        # content +=  para.text
    # print(content)

    Exam_jineng(title=title,title_content=content).save()

def query(path):#获取所有存放word文件的路径
    all_docx_paths = []
    for i in os.walk(path):
        # print(i)
        if len(i[1])==0:
            for j in i[2]:
                print(j)
                if j.strip().endswith('.docx') and bool(j.find('人工智能')+1):
                    all_docx_paths.append(os.path.join(i[0],j))
    for i in all_docx_paths:
        writeToDB(i)
        print(i)
        # break
    return all_docx_paths
# Create your views here.
#读取数据并存储
def readjineng(request):
    docxpath = r'C:\Users\gao10\Desktop\201811考题'
    query(docxpath)   #读取数据并存储
    return HttpResponse('更新成功')

#显示界面
def showjineng(request):
    if request.method == 'GET':
        # readjineng(request)
        jineng = Exam_jinengForm()
        lilun = LilunForm()
        kaotiform = KaotiForm()
        return render(request,'readjineng/showExams_jineng.html',locals())
    else:
        post = request.POST
        print('post:',post)
        Exams_jineng_id = post.get('id').strip()
        print('======Exams_jineng_id',Exams_jineng_id)

        Exams_jinengs = list(Exam_jineng.objects.filter(id = Exams_jineng_id).values())
        print(Exams_jinengs)

        return HttpResponse(json.dumps(Exams_jinengs))

def showjineng1(request):
    get = request.GET
    id = get.get('id','none').strip()
    if id=='none':
        return render(request,'readjineng/showExams_jineng1.html',locals())
    else:
        id = int(id)
        print('id:',id)
        exam_jineng = Exam_jineng.objects.get(id=id)
        print(exam_jineng)
        return render(request, 'readjineng/showExams_jineng1.html', {'exam_jineng':exam_jineng,'display':'pre{display: block;}'})

readJineng/templates/readjineng/showExams_jineng.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <script src="/static/bootstrap/js/jquery-2.1.4.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>

    <title>试卷查询</title>
</head>
<body>

{#    <table id="show_table" class="table">#}
{##}
{#    </table>#}
    <div id="lilun">
       {{ kaotiform.kaoti }}
        <button onclick="jinsuo(this);" class="btn btn-default">紧缩</button>
        <table id="show_table" class="table">

        </table>
    </div>
    <script>
        function jinsuo(self) {
            $('.table tr,td').css('padding','0px')
        }
        $('#id_kaoti').change(function () {
            $('#show_table').text('')
            $.ajax({
                url: '/xlsshow/',
                type: 'post',
                data: {id:$(this).val()},
                dataType: 'json',
                success: function (arg) {
                    console.log(arg);
                    $.each(arg,function (x,y) {
                        tr = $('<tr></tr>')


                        th = $('<th></th>')
                        p = $('<span>'+y.bianhao+'、</span>');th.append(p[0])
                        p = $('<span>('+y.leixing.substring(2)+')</span>');th.append(p[0])
                        p = $('<span>'+y.tigan+'</span>');th.append(p[0])
                        tr.append(th[0])


                        td1 = $('<td></td>')
                        if(y.leixing.substring(2)=='判断'){
                            if(y.daan.trim()=='A'){
                                p = $('<p>答案：<span style="color:red;">'+'正确'+'</span></p>');td1.append(p[0])
                            }
                            if(y.daan.trim()=='B'){
                                p = $('<p>答案：<span style="color:red;">'+'错误'+'</span></p>');td1.append(p[0])
                            }
                            tr.append(td1)
                        }else{
                            td2 = $('<td></td>');p = $('<p>A、'+y.xxa+'</p>');td2.append(p);tr.append(td2)
                            td3 = $('<td></td>');p = $('<p>B、'+y.xxb+'</p>');td3.append(p);tr.append(td3)
                            td4 = $('<td></td>');p = $('<p>C、'+y.xxc+'</p>');td4.append(p);tr.append(td4)
                            td5 = $('<td></td>');p = $('<p>D、'+y.xxd+'</p>');td5.append(p);tr.append(td5)
                            td6 = $('<td></td>');p = $('<p>答案：<span style="color:red;">'+y.daan+'</span></p>');td6.append(p);tr.append(td6)
                        }

                        $('#show_table').append(tr)
                        {#$('div').css()#}
                    })
                }
            })
        })

    </script>
    <div id="jineng">
        {{ lilun.name }}
{#        <button onclick="jinsuo(this);" class="btn btn-default">紧缩</button>#}
        <iframe src="/showlilun/" frameborder="0" scrolling="auto" id="jinengiframe">

        </iframe>
    </div>
    <script>
        function jinsuo(self) {
            $('.table tr,td').css('padding','0px')
        }
        $('#id_name').change(function () {
            {#$('#jinengiframe').attr('src','/showjineng1/?id='+$(this).val())#}
            $('#jinengiframe').attr('src','/showlilun/?id='+$(this).val())
            {#$('#jinengiframe pre').css('display','block')#}
            {#$('#show_table').text('')#}
            {#$.ajax({#}
            {#    url: '',#}
            {#    type: 'post',#}
            {#    data: {id:$(this).val()},#}
            {#    dataType: 'json',#}
            {#    success: function (arg) {#}
            {##}
            {##}
                    {#console.log(arg);#}
                    {#$.each(arg,function (x,y) {#}
                    {#    tr = $('<tr></tr>')#}
                    {#    th = $('<th></th>');tr.append(th[0])#}
                    {#    p = $('<span>'+y.title+'</span>');th.append(p[0])#}
                    {#    $('#show_table').append(tr)#}
                    {##}
                    {#    tr1 = $('<tr></tr>')#}
                    {#    td1 = $('<td></td>');tr1.append(td1[0])#}
                    {#    p1 = $('<pre>'+y.title_content +'</pre>');td1.append(p1[0])#}
                    {#    tr.append(td1[0])#}
                    {##}
                    {#    $('#show_table').append(tr1)#}
                    {#})#}
            {##}
            {#    }#}
            {#})#}
        })

    </script>
    <style>
            body{
                margin: 0 auto;
                background-color: gainsboro;
            }
            tr,td{
                display: block;
            }
            .table{
                width: 100%;
            }
            #viewcount{
                color: orangered;
                transition: 1s;
                opacity: 0;
            }
            #viewcount:hover{
                opacity: 1;
            }
            #advertising{
                width: 50px;
                height: 380px;
                position: fixed;
                right: 0px;
                top:30px;
                text-align: center;
                font-size:35px;
                font-weight: 600;
                background-color: rgba(200,200,200,0.5);
            }
        iframe{
            width: 100%;
            display: block;
            height: 1000px;
            overflow:scroll;
        }
        #jineng{
            width: 50%;
            float: right;

        }
        #lilun{
            width:50%;
            float:left;
            border-right:1px solid gray;
        }
    </style>
</body>
</html>

readJineng/templates/readjineng/showExams_jineng1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <script src="/static/bootstrap/js/jquery-2.1.4.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>

    <title>试卷查询</title>
</head>
<body>
    <table id="show_table" class="table">
        <tr>
            <th>{{ exam_jineng.title }}</th>
            <td><pre>{{ exam_jineng.title_content }}</pre></td>
        </tr>
    </table>
    <script>
        function jinsuo(self) {
            $('.table tr,td').css('padding','0px')
        }

    </script>
    <style>
            body{
                margin: 0 auto;
                background-color: gainsboro;
            }
            tr,td{
                display: block;
            }
            pre{
                white-space:pre-wrap;
                word-wrap:break-word;
            }
            .table{
                width: 100%;
            }
            #viewcount{
                color: orangered;
                transition: 1s;
                opacity: 0;
            }
            #viewcount:hover{
                opacity: 1;
            }
            #advertising{
                width: 50px;
                height: 380px;
                position: fixed;
                right: 0px;
                top:30px;
                text-align: center;
                font-size:35px;
                font-weight: 600;
                background-color: rgba(200,200,200,0.5);
            }
            pre{
                display: none;
            }
            {{ display }}
    </style>
</body>
</html>